### PR TITLE
sort.py changed by adding floyd warshall algo into it

### PR DESCRIPTION
**Pull request by ashwinitanpure**
Please check out my PR

### CODE REVIEW

**Comment by devkapilbansal** [comment]
Hi @ashwinitanpure you are not required to change the initial code. If you want to add new sorting algo, then add a function related to it.

**Review by devkapilbansal — COMMENTED** [review]
Also, add tests for your code

**Comment by ashwinitanpure** [comment]
ok..Thanks..I will do so

**Comment by codesankalp** [comment]
@ashwinitanpure we will not approve your pull request until it's linked with an issue.
Linking the issue with pull request is a must step.
Also make the code changes as mengtioned by @devkapilbansal

**Comment by ashwinitanpure** [comment]
ok

**Comment by devkapilbansal** [comment]
@ashwinitanpure It would be better if you open a relevant issue for this too and I will assign this to you

**Comment by Aryamanz29** [comment]
Closing this PR, Due to inactivity

**Pull request closed without merging**
