### PR TITLE
Solved Create all Binary Tree Traversals

### PR DESCRIPTION
**Pull request by milanj-1**

### CODE REVIEW

**Comment by codesankalp** [comment]
@milanj-1 we will not approve or review your pull request until it's linked with an issue.
Linking the issue with pull request is a must step.

**Comment by milanj-1** [comment]
how do you link the issue to pull request?

**Comment by devkapilbansal** [comment]
> how do you link the issue to pull request?

In your commit write commit message as

[type] short description

Closes #ssue_no

**Comment by codesankalp** [comment]
@milanj-1 it's been 3 days and you haven't changed anything so marking it as invalid.

**Pull request closed without merging**
