### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Harjot9812**

### CODE REVIEW

**Comment by codesankalp** [comment]
@Harjot9812 your pull request will not be reviewed untill it's linked with the issue.
to know how to link issue with pull request search google.

**Comment by devkapilbansal** [comment]
@Harjot9812 you need to ask for an issue first before making a pull request

**Comment by codesankalp** [comment]
@Harjot9812 please link the issue and comment on the issue for the assignment of the issue to you.
We welcome new contributors but don't forget to read our contributing guidelines and pull request guidelines.

**Comment by devkapilbansal** [comment]
Doesn't seem relevant in any sense.

**Pull request closed without merging**
