### PR TITLE
Added Files Bit Manipulation and Project Euler

### PR DESCRIPTION
**Pull request by cratiavi**
### Description

Added topic BIT Manipulation to the folder DS ALGO. Added problem solution to project Euler site questions.

### Related Issue

** Please don't create a Pull request without creating an issue first **

Fixes # [ISSUE]
#76

### Type of Change:

Documentation change-Added new files.

- Code
- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)

### Motivation and Context

To contribute to open source by sharing my knowledge towards this domain.

### How Has This Been Tested?

Ran on my IDE and it was working fine.

### Checklist:

- [x] I read the **CONTRIBUTING** document before making this pull request
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] My change requires change to documentation
- [x] I have updated documentation accordingly
- [x] I have updated the requirements file
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by codesankalp** [comment]
@cratiavi please link your issue and improve commit message.

**Comment by cratiavi** [comment]
@codesankalp Done please verify the changes made.

**Comment by codesankalp** [comment]
@cratiavi how do you improved the commit message and linked the issue ?
to change the things mentioned above use Fixes #issue_no and squash our commits into one commit message headline must not be uploaded files.
There are three commits now convert them into one.

**Comment by cratiavi** [comment]
@codesankalp Now please verify . Things fixed,
1.Issue generated.
2.Commits Converted to 1.

**Comment by devkapilbansal** [comment]
@cratiavi closing this as we are building a library for python. So, don't require exact solution or wants to solve a problem.

**Comment by cratiavi** [comment]
Fine.

**Pull request closed without merging**
