### PR TITLE
Add shell sort algorithm

### LINKED ISSUE #22: Implement "shell sort" algorithm ref: issue #4

### PR DESCRIPTION
**Pull request by destag**
Closes #22

### CODE REVIEW

**Comment by codesankalp** [comment]
write brief commit message. read commit guidelines.

**Review by devkapilbansal — COMMENTED** [review]
Great work @destag can you please add tests too

**Comment by codesankalp** [comment]
@destag are you still working on this?

**Comment by destag** [comment]
Yes, I'm working on that. Sorry for the delay

**Comment by devkapilbansal** [comment]
Okay, @destag also update your branch with current master to resolve conflicts

**Comment by destag** [comment]
Sorry, I don't have much time to work on that.

**Pull request closed without merging**
