### PR TITLE
[docs] Modified Contributing.md #36

### LINKED ISSUE #36: Improve contributing.md
## Description
After reviewing some pull requests, I realised that we don't have strict guidelines in contributing files. Here are some changes I would suggest: 

- We should use conventional commit guidelines. This link may help https://www.conventionalcommits.org/en/v1.0.0/

We can add a commit template later for this

- Before working on an issue, you should get it assigned.

- If an issue is assigned to you, be sure to post updates. Otherwise, the assignee would be removed after 3 days of inactivity

- You should make a branch other than the default branch for the pull request.

### PR DESCRIPTION
**Pull request by Aryamanz29**
-Added contributing guidelines for new contributors.
closes #36

### CODE REVIEW

**Comment by codesankalp** [comment]
@Aryamanz29 to get your pull request reviewed please link this pull request with the issue.

**Comment by Aryamanz29** [comment]
repo deleted so again creating this PR.

**Comment by devkapilbansal** [comment]
@Aryamanz29 don't do that

**Comment by devkapilbansal** [comment]
Use same branch name as earlier and reopen this pull request

**Pull request closed without merging**
